// This file is auto-generated by Lovable. Do not modify it.

import { createLovableAuth } from "@lovable.dev/cloud-auth-js";
import { supabase } from "../supabase/client";
const lovableAuth = createLovableAuth();

type SignInOptions = {
  redirect_uri?: string;
  extraParams?: Record<string, string>;
};

export const lovable = {
  auth: {
    signInWithOAuth: async (provider: "google" | "apple" | "microsoft" | "lovable", opts?: SignInOptions) => {
      const { data, error } = await supabase.auth.signInWithOAuth({
        provider: provider === "google" ? "google" : (provider as any),
        options: {
          redirectTo: opts?.redirect_uri || `${window.location.origin}/dashboard`,
        },
      });

      if (error) {
        return { error };
      }

      return { redirected: true };
    },
  },
};
